steps:
- name: node:14.10.0
  entrypoint: npm
  args: ['install']
- name: node:14.10.0
  entrypoint: npm
  args: ['test']
- name: node:14.10.0
  entrypoint: npm
  args: ['run', 'build']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: 
    - -c
    - | 
      if [[ "$BRANCH_NAME" == "main" ]]
      then
        'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy'
      else
        echo "Skipping deploy"
      fi
timeout: '1600s'
